# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:  
  L-TEMPLATE.api:
    build:
      dockerfile: ./rfsmart.phoenix.L-TEMPLATE.web/dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_TOKEN: ${NUGET_TOKEN}
    ports:
      - "5010:5010"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5010' || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - phoenix

  L-TEMPLATE.tests:
    image: L-TEMPLATE-integration-tests
    build:
      dockerfile: ./rfsmart.phoenix.L-TEMPLATE.tests/dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_TOKEN: ${NUGET_TOKEN}
    depends_on:
      L-TEMPLATE.api:
        condition: service_healthy
    environment:
      DOTNET_ENVIRONMENT: "Development"
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      IntegrationTestSettings__AppUrl: "http://L-TEMPLATE.api:5010"
    networks:
      - phoenix
    volumes:
      - $HOME$USERPROFILE/.aws:/root/.aws:ro

networks:
  phoenix:
    driver: bridge